"""add morning report models

Revision ID: 0e3c5cecf181
Revises: 
Create Date: 2026-08-03 13:51:59.758048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e3c5cecf181'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('date_format', sa.String(length=20), nullable=False),
    sa.Column('decimal_separator', sa.String(length=1), nullable=False),
    sa.Column('thousands_separator', sa.String(length=1), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('subscription_plan', sa.String(length=20), nullable=False),
    sa.Column('subscription_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('key_prefix', sa.String(length=8), nullable=False),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=False)
    op.create_index(op.f('ix_api_keys_key_prefix'), 'api_keys', ['key_prefix'], unique=False)
    op.create_index(op.f('ix_api_keys_tenant_id'), 'api_keys', ['tenant_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('changed_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('previous_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('performed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('performed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_table('file_uploads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='upload_status'), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('s3_path', sa.String(length=500), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('processed_rows', sa.Integer(), nullable=False),
    sa.Column('error_rows', sa.Integer(), nullable=False),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_processing_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uploaded_by_user_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_uploads_tenant_id'), 'file_uploads', ['tenant_id'], unique=False)
    op.create_table('institutions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('institution_type', sa.String(length=50), nullable=False),
    sa.Column('settlement_delay_days', sa.Integer(), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('bank_connection_provider', sa.String(length=50), nullable=True),
    sa.Column('bank_connection_requisition_id', sa.String(length=255), nullable=True),
    sa.Column('bank_connection_account_iban', sa.String(length=34), nullable=True),
    sa.Column('bank_connection_last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bank_connection_status', sa.String(length=20), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_institution_tenant_code')
    )
    op.create_index(op.f('ix_institutions_code'), 'institutions', ['code'], unique=False)
    op.create_index(op.f('ix_institutions_tenant_id'), 'institutions', ['tenant_id'], unique=False)
    op.create_table('morning_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('total_collections', sa.Integer(), nullable=False),
    sa.Column('matched_count', sa.Integer(), nullable=False),
    sa.Column('partial_count', sa.Integer(), nullable=False),
    sa.Column('unmatched_count', sa.Integer(), nullable=False),
    sa.Column('discrepancy_count', sa.Integer(), nullable=False),
    sa.Column('actual_bank_balance', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('projected_incoming_7d', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('projected_incoming_30d', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_pending_clearance', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_fees_yesterday', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('fee_discrepancies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('alerts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('uncleared_collection_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('discrepancy_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('report_html', sa.Text(), nullable=True),
    sa.Column('report_text', sa.Text(), nullable=True),
    sa.Column('report_pdf_url', sa.String(length=500), nullable=True),
    sa.Column('email_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_recipients', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('webhook_delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'report_date', name='uq_report_tenant_date')
    )
    op.create_index(op.f('ix_morning_reports_report_date'), 'morning_reports', ['report_date'], unique=False)
    op.create_index(op.f('ix_morning_reports_tenant_id'), 'morning_reports', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', postgresql.ENUM('OWNER', 'ADMIN', 'ACCOUNTANT', 'VIEWER', name='user_role'), nullable=False),
    sa.Column('auth_provider', sa.String(length=50), nullable=False),
    sa.Column('auth_subject', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notification_email', sa.Boolean(), nullable=False),
    sa.Column('notification_webhook', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_auth_subject'), 'users', ['auth_subject'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('webhooks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('events', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('secret', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_delivery_status', sa.String(length=20), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhooks_tenant_id'), 'webhooks', ['tenant_id'], unique=False)
    op.create_table('bank_movements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('statement_date', sa.Date(), nullable=False),
    sa.Column('value_date', sa.Date(), nullable=False),
    sa.Column('booking_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('account_iban', sa.String(length=34), nullable=True),
    sa.Column('movement_type', postgresql.ENUM('CREDIT', 'DEBIT', 'FEE', 'CHARGE', 'CHARGEBACK', name='movement_type'), nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=False),
    sa.Column('concept', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('matched_collection_id', sa.UUID(), nullable=True),
    sa.Column('is_reconciled', sa.Boolean(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_file_upload_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matched_collection_id'], ['card_collections.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['source_file_upload_id'], ['file_uploads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_movements_reference'), 'bank_movements', ['reference'], unique=False)
    op.create_index(op.f('ix_bank_movements_tenant_id'), 'bank_movements', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_bank_movements_value_date'), 'bank_movements', ['value_date'], unique=False)
    op.create_index('ix_bank_mv_date_inst', 'bank_movements', ['value_date', 'institution_id'], unique=False)
    op.create_index('ix_bank_mv_matched', 'bank_movements', ['matched_collection_id'], unique=False)
    op.create_index('ix_bank_mv_reference', 'bank_movements', ['reference'], unique=False)
    op.create_table('card_collections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('collection_date', sa.Date(), nullable=False),
    sa.Column('upload_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('card_type', postgresql.ENUM('DEBIT', 'CREDIT', name='transaction_type'), nullable=False),
    sa.Column('terminal_id', sa.String(length=100), nullable=True),
    sa.Column('batch_number', sa.String(length=100), nullable=True),
    sa.Column('reference', sa.String(length=255), nullable=False),
    sa.Column('amount_gross', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('amount_net', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('card_last_digits', sa.String(length=4), nullable=True),
    sa.Column('transaction_count', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'MATCHED', 'PARTIAL', 'UNMATCHED', 'DISCREPANCY', 'CLEARED', name='reconciliation_status'), nullable=False),
    sa.Column('matched_bank_movement_id', sa.UUID(), nullable=True),
    sa.Column('matched_tpv_report_id', sa.UUID(), nullable=True),
    sa.Column('expected_settlement_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_file_upload_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matched_bank_movement_id'], ['bank_movements.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['matched_tpv_report_id'], ['tpv_closing_reports.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['source_file_upload_id'], ['file_uploads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_collections_batch_number'), 'card_collections', ['batch_number'], unique=False)
    op.create_index(op.f('ix_card_collections_collection_date'), 'card_collections', ['collection_date'], unique=False)
    op.create_index(op.f('ix_card_collections_reference'), 'card_collections', ['reference'], unique=False)
    op.create_index(op.f('ix_card_collections_status'), 'card_collections', ['status'], unique=False)
    op.create_index(op.f('ix_card_collections_tenant_id'), 'card_collections', ['tenant_id'], unique=False)
    op.create_index('ix_collections_date_inst_status', 'card_collections', ['collection_date', 'institution_id', 'status'], unique=False)
    op.create_index('ix_collections_reference', 'card_collections', ['reference'], unique=False)
    op.create_index('ix_collections_tenant_date', 'card_collections', ['tenant_id', 'collection_date'], unique=False)
    op.create_table('fee_structures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('card_type', postgresql.ENUM('DEBIT', 'CREDIT', name='transaction_type'), nullable=False),
    sa.Column('fee_type', postgresql.ENUM('PERCENTAGE', 'FLAT', 'MIXED', 'TIERED', name='fee_type'), nullable=False),
    sa.Column('percentage_rate', sa.Numeric(precision=8, scale=5), nullable=False),
    sa.Column('flat_rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('min_fee', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('max_fee', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tier_thresholds', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('vat_included', sa.Boolean(), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_until', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_structures_institution_id'), 'fee_structures', ['institution_id'], unique=False)
    op.create_index(op.f('ix_fee_structures_tenant_id'), 'fee_structures', ['tenant_id'], unique=False)
    op.create_table('tpv_closing_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('terminal_id', sa.String(length=100), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('opening_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closing_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_sales_gross', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_refunds', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_net', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('transaction_count', sa.Integer(), nullable=False),
    sa.Column('debit_sales', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('credit_sales', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('batch_number', sa.String(length=100), nullable=True),
    sa.Column('z_report_number', sa.String(length=100), nullable=True),
    sa.Column('matched_collection_id', sa.UUID(), nullable=True),
    sa.Column('discrepancies', sa.Text(), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_file_upload_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matched_collection_id'], ['card_collections.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['source_file_upload_id'], ['file_uploads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tpv_batch', 'tpv_closing_reports', ['batch_number'], unique=False)
    op.create_index(op.f('ix_tpv_closing_reports_batch_number'), 'tpv_closing_reports', ['batch_number'], unique=False)
    op.create_index(op.f('ix_tpv_closing_reports_report_date'), 'tpv_closing_reports', ['report_date'], unique=False)
    op.create_index(op.f('ix_tpv_closing_reports_tenant_id'), 'tpv_closing_reports', ['tenant_id'], unique=False)
    op.create_index('ix_tpv_date_inst', 'tpv_closing_reports', ['report_date', 'institution_id'], unique=False)
    op.create_table('cash_flow_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('entry_type', sa.String(length=50), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('source_collection_id', sa.UUID(), nullable=True),
    sa.Column('expected_value_date', sa.Date(), nullable=True),
    sa.Column('running_balance', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_collection_id'], ['card_collections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_flow_entries_entry_date'), 'cash_flow_entries', ['entry_date'], unique=False)
    op.create_index(op.f('ix_cash_flow_entries_tenant_id'), 'cash_flow_entries', ['tenant_id'], unique=False)
    op.create_index('ix_cashflow_date_type', 'cash_flow_entries', ['entry_date', 'entry_type'], unique=False)
    op.create_table('reconciliation_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('collection_id', sa.UUID(), nullable=False),
    sa.Column('collection_date', sa.Date(), nullable=False),
    sa.Column('bank_movement_id', sa.UUID(), nullable=True),
    sa.Column('tpv_report_id', sa.UUID(), nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'MATCHED', 'PARTIAL', 'UNMATCHED', 'DISCREPANCY', 'CLEARED', name='reconciliation_status'), nullable=False),
    sa.Column('match_confidence', sa.String(length=20), nullable=True),
    sa.Column('gross_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('bank_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('tpv_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('calculated_fee', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('actual_fee_deduction', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('fee_discrepancy', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('amount_discrepancy', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('days_to_clear', sa.Integer(), nullable=True),
    sa.Column('uncleared_reason', sa.Text(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_by_user_id', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bank_movement_id'], ['bank_movements.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['collection_id'], ['card_collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tpv_report_id'], ['tpv_closing_reports.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'collection_id', name='uq_recon_tenant_collection')
    )
    op.create_index('ix_recon_collection', 'reconciliation_results', ['collection_id'], unique=False)
    op.create_index('ix_recon_status_date', 'reconciliation_results', ['status', 'collection_date'], unique=False)
    op.create_index(op.f('ix_reconciliation_results_collection_date'), 'reconciliation_results', ['collection_date'], unique=False)
    op.create_index(op.f('ix_reconciliation_results_status'), 'reconciliation_results', ['status'], unique=False)
    op.create_index(op.f('ix_reconciliation_results_tenant_id'), 'reconciliation_results', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reconciliation_results_tenant_id'), table_name='reconciliation_results')
    op.drop_index(op.f('ix_reconciliation_results_status'), table_name='reconciliation_results')
    op.drop_index(op.f('ix_reconciliation_results_collection_date'), table_name='reconciliation_results')
    op.drop_index('ix_recon_status_date', table_name='reconciliation_results')
    op.drop_index('ix_recon_collection', table_name='reconciliation_results')
    op.drop_table('reconciliation_results')
    op.drop_index('ix_cashflow_date_type', table_name='cash_flow_entries')
    op.drop_index(op.f('ix_cash_flow_entries_tenant_id'), table_name='cash_flow_entries')
    op.drop_index(op.f('ix_cash_flow_entries_entry_date'), table_name='cash_flow_entries')
    op.drop_table('cash_flow_entries')
    op.drop_index('ix_tpv_date_inst', table_name='tpv_closing_reports')
    op.drop_index(op.f('ix_tpv_closing_reports_tenant_id'), table_name='tpv_closing_reports')
    op.drop_index(op.f('ix_tpv_closing_reports_report_date'), table_name='tpv_closing_reports')
    op.drop_index(op.f('ix_tpv_closing_reports_batch_number'), table_name='tpv_closing_reports')
    op.drop_index('ix_tpv_batch', table_name='tpv_closing_reports')
    op.drop_table('tpv_closing_reports')
    op.drop_index(op.f('ix_fee_structures_tenant_id'), table_name='fee_structures')
    op.drop_index(op.f('ix_fee_structures_institution_id'), table_name='fee_structures')
    op.drop_table('fee_structures')
    op.drop_index('ix_collections_tenant_date', table_name='card_collections')
    op.drop_index('ix_collections_reference', table_name='card_collections')
    op.drop_index('ix_collections_date_inst_status', table_name='card_collections')
    op.drop_index(op.f('ix_card_collections_tenant_id'), table_name='card_collections')
    op.drop_index(op.f('ix_card_collections_status'), table_name='card_collections')
    op.drop_index(op.f('ix_card_collections_reference'), table_name='card_collections')
    op.drop_index(op.f('ix_card_collections_collection_date'), table_name='card_collections')
    op.drop_index(op.f('ix_card_collections_batch_number'), table_name='card_collections')
    op.drop_table('card_collections')
    op.drop_index('ix_bank_mv_reference', table_name='bank_movements')
    op.drop_index('ix_bank_mv_matched', table_name='bank_movements')
    op.drop_index('ix_bank_mv_date_inst', table_name='bank_movements')
    op.drop_index(op.f('ix_bank_movements_value_date'), table_name='bank_movements')
    op.drop_index(op.f('ix_bank_movements_tenant_id'), table_name='bank_movements')
    op.drop_index(op.f('ix_bank_movements_reference'), table_name='bank_movements')
    op.drop_table('bank_movements')
    op.drop_index(op.f('ix_webhooks_tenant_id'), table_name='webhooks')
    op.drop_table('webhooks')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_auth_subject'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_morning_reports_tenant_id'), table_name='morning_reports')
    op.drop_index(op.f('ix_morning_reports_report_date'), table_name='morning_reports')
    op.drop_table('morning_reports')
    op.drop_index(op.f('ix_institutions_tenant_id'), table_name='institutions')
    op.drop_index(op.f('ix_institutions_code'), table_name='institutions')
    op.drop_table('institutions')
    op.drop_index(op.f('ix_file_uploads_tenant_id'), table_name='file_uploads')
    op.drop_table('file_uploads')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_api_keys_tenant_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_prefix'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
